apiVersion: v1
kind: Service
metadata:
  name: node-blog-app
  labels:
    app: node-blog-app
spec:
  type: NodePort
  selector:
    app: node-blog-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
  - name: postgres
    port: 5432
    targetPort: 5432
